version: "3.4"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: typeorm
      MYSQL_DATABASE: typeorm
      MYSQL_USER: typeorm
      MYSQL_PASSWORD: typeorm
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin",
        "--default-authentication-plugin=mysql_native_password",
        "--sync-binlog=0",
        "--innodb-flush-log-at-trx-commit=2",
        "--innodb-use-native-aio=0",
      ]
